site_name: Tiger's Digital Garden
docs_dir: notes
theme:
  name: material
  favicon: images/favicon.webp
markdown_extensions:
  - attr_list
  - md_in_html
  # support `- [ ]` github styled checkbox
  - pymdownx.tasklist:
      custom_checkbox: true
  # support mermaid diagram
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
